image: docker:git
services:
  - docker:dind

before_script:
  - docker info

build_image:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/
    - docker build -t registry.gitlab.com/kathra/kathra/kathra-services/kathra-dashboard/angular/kathra-dashboard-angular:latest .
    - docker push /kathra/kathra/kathra-services/kathra-dashboard/angular/kathra-dashboard-angular:latest