image: docker:git
services:
  - docker:dind

variables:
  IMAGE_REF: $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME/\//-}


before_script:
  - docker info

build_image:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/
    - docker build -t $IMAGE_REF .
    - docker push $IMAGE_REF