---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "${DESC}"
  labels:
    product: "${PRODUCT_NAME}"
    app: "${SERVICE_NAME}"
  name: "${SERVICE_NAME}-${IMPL_NAME}"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: "${SERVICE_NAME}-${IMPL_NAME}"
    labels:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
      impl: "${IMPL_NAME}"
  spec:
    replicas: '1'
    template:
      metadata:
        labels:
          product: "${PRODUCT_NAME}"
          app: "${SERVICE_NAME}"
          impl: "${IMPL_NAME}"
      spec:
        imagePullSecrets:
        - name: regcred
        containers:
        - name: "${SERVICE_NAME}-${IMPL_NAME}"
          image: "${IMAGE_NAME}"
          ports:
          - name: web
            containerPort: ${PORT}
            protocol: TCP
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: PLATFORM_MGR_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: PLATFORM_MGR_ENDPOINT
                name: dashboard-config
          - name: APP_MGR_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: APP_MGR_ENDPOINT
                name: dashboard-config
          - name: PIPELINE_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: PIPELINE_ENDPOINT
                name: dashboard-config
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_REALM
                name: keycloak-config
          - name: KEYCLOAK_AUTH_URL
            valueFrom:
              configMapKeyRef:
                key: KEYCLOAK_AUTH_URL
                name: keycloak-config
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_CLIENT_ID
                name: keycloak-secret
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: KEYCLOAK_CLIENT_SECRET
                name: keycloak-secret
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICE_NAME}"
    labels:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
      expose: true
  spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: ${PORT}
    selector:
      product: "${PRODUCT_NAME}"
      app: "${SERVICE_NAME}"
    type: ClusterIP
    sessionAffinity: None