/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ApiFileValidationResponse { 
    format?: ApiFileValidationResponse.FormatEnum;
    /**
     * Service's name
     */
    name?: string;
    /**
     * Service's groupId
     */
    groupId?: string;
    /**
     * Service's version
     */
    version?: string;
    /**
     * Contains operations
     */
    operations?: boolean;
    /**
     * Contains model
     */
    model?: boolean;
}
export namespace ApiFileValidationResponse {
    export type FormatEnum = 'json' | 'yaml' | 'invalid';
    export const FormatEnum = {
        Json: 'json' as FormatEnum,
        Yaml: 'yaml' as FormatEnum,
        Invalid: 'invalid' as FormatEnum
    };
}
