/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BinaryRepository } from './binaryRepository';
import { CatalogEntry } from './catalogEntry';
import { Pipeline } from './pipeline';
import { Resource } from './resource';
import { SourceRepository } from './sourceRepository';


export interface Asset extends Resource { 
    binaryRepository?: BinaryRepository;
    sourceRepository?: SourceRepository;
    pipeline?: Pipeline;
    catalogEntries?: Array<CatalogEntry>;
}
