/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Group } from './group';
import { Resource } from './resource';


export interface BinaryRepository extends Resource { 
    group?: Group;
    type?: any;
    provider?: string;
    providerId?: string;
    url?: string;
    snapshot?: boolean;
}
