/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type BINARYREPOSITORYTYPE = 'JAVA' | 'PYTHON' | 'DOCKER_IMAGE' | 'HELM';

export const BINARYREPOSITORYTYPE = {
    JAVA: 'JAVA' as BINARYREPOSITORYTYPE,
    PYTHON: 'PYTHON' as BINARYREPOSITORYTYPE,
    DOCKERIMAGE: 'DOCKER_IMAGE' as BINARYREPOSITORYTYPE,
    HELM: 'HELM' as BINARYREPOSITORYTYPE
};
