/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BuildArgument } from './buildArgument';


export interface Build {
    /**
     * Build identifier
     */
    buildNumber?: string;
    /**
     * Pipeline path
     */
    path?: string;
    /**
     * Branch or Tag
     */
    commitLabel?: string;
    /**
     * Commit id
     */
    commitId?: string;
    /**
     * Build date (UTC timestamp)
     */
    creationDate?: number;
    /**
     * Duration in seconds
     */
    duration?: number;
    /**
     * Build status
     */
    status?: Build.StatusEnum;
    /**
     * Additional Build arguments
     */
    buildArguments?: Array<BuildArgument>;
    /**
     * Build logs
     */
    logs?: string;
}
export namespace Build {
    export type StatusEnum = 'scheduled' | 'processing' | 'success' | 'failed';
    export const StatusEnum = {
        Scheduled: 'scheduled' as StatusEnum,
        Processing: 'processing' as StatusEnum,
        Success: 'success' as StatusEnum,
        Failed: 'failed' as StatusEnum
    }
}
