/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CatalogResourceParameterDependency {
    name?: string;
    condition?: CatalogResourceParameterDependency.ConditionEnum;
    value?: string;
}
export namespace CatalogResourceParameterDependency {
    export type ConditionEnum = 'is' | 'isNot';
    export const ConditionEnum = {
        Is: 'is' as ConditionEnum,
        IsNot: 'isNot' as ConditionEnum
    }
}
