/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogEntryArgument } from './catalogEntryArgument';
import { CatalogEntryPackage } from './catalogEntryPackage';


export interface CatalogEntryPackageVersion { 
    catalogEntryPackage?: CatalogEntryPackage;
    /**
     * Version
     */
    version?: string;
    /**
     * Documentation of catalog entry (Markdown)
     */
    documentation?: string;
    /**
     * Catalog entry arguments
     */
    arguments?: Array<CatalogEntryArgument>;
}
