/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CatalogEntryArgument { 
    /**
     * Readable argument for catalog entry
     */
    label?: string;
    /**
     * Description argument for catalog entry
     */
    description?: string;
    /**
     * Argument key for catalog entry
     */
    key?: string;
    /**
     * Argument value for catalog entry
     */
    value?: string;
    /**
     * Argument constraint for catalog entry
     */
    contrainst?: string;
}
