/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Resource } from './resource';


export interface CatalogResourceParameterValidationRule {
    id?: string;
    name?: string;
    metadata?: { [key: string]: any; };
    type?: CatalogResourceParameterValidationRule.TypeEnum;
    value?: string;
    prompt?: string;
}
export namespace CatalogResourceParameterValidationRule {
    export type TypeEnum = 'empty' | 'alphaNum' | 'minValue' | 'maxValue' | 'minLength' | 'maxLength';
    export const TypeEnum = {
        Empty: 'empty' as TypeEnum,
        AlphaNum: 'alphaNum' as TypeEnum,
        MinValue: 'minValue' as TypeEnum,
        MaxValue: 'maxValue' as TypeEnum,
        MinLength: 'minLength' as TypeEnum,
        MaxLength: 'maxLength' as TypeEnum
    }
}
