/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogResourceParameterDependency } from './catalogResourceParameterDependency';
import { CatalogResourceParameterValidationRule } from './catalogResourceParameterValidationRule';


export interface CatalogResourceParameter {
    name?: string;
    optional?: boolean;
    type?: CatalogResourceParameter.TypeEnum;
    defaultValue?: string;
    description?: string;
    label?: string;
    rules?: Array<CatalogResourceParameterValidationRule>;
    depends?: Array<CatalogResourceParameterDependency>;
}
export namespace CatalogResourceParameter {
    export type TypeEnum = 'text' | 'float' | 'integer' | 'secret' | 'boolean' | 'select';
    export const TypeEnum = {
        Text: 'text' as TypeEnum,
        Float: 'float' as TypeEnum,
        Integer: 'integer' as TypeEnum,
        Secret: 'secret' as TypeEnum,
        Boolean: 'boolean' as TypeEnum,
        Select: 'select' as TypeEnum
    }
}
