/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnvironmentResource } from './environmentResource';
import { Resource } from './resource';


export interface Environment {
    id?: string;
    name?: string;
    metadata?: { [key: string]: any; };
    resources?: Array<EnvironmentResource>;
    status?: Environment.StatusEnum;
}
export namespace Environment {
    export type StatusEnum = 'deploying' | 'available' | 'deleting' | 'failsafe' | 'error';
    export const StatusEnum = {
        Deploying: 'deploying' as StatusEnum,
        Available: 'available' as StatusEnum,
        Deleting: 'deleting' as StatusEnum,
        Failsafe: 'failsafe' as StatusEnum,
        Error: 'error' as StatusEnum
    }
}
