/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EnvironmentResourceParameter {
    name?: string;
    value?: string;
    type?: EnvironmentResourceParameter.TypeEnum;
}
export namespace EnvironmentResourceParameter {
    export type TypeEnum = 'integer' | 'string' | 'float' | 'boolean';
    export const TypeEnum = {
        Integer: 'integer' as TypeEnum,
        String: 'string' as TypeEnum,
        Float: 'float' as TypeEnum,
        Boolean: 'boolean' as TypeEnum
    }
}
