/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assignation } from './assignation';
import { BinaryRepository } from './binaryRepository';
import { Resource } from './resource';
import { User } from './user';


export interface Group extends Resource { 
    /**
     * Group's path in case of subgroup
     */
    path?: string;
    technicalUser?: User;
    binaryRepositories?: Array<BinaryRepository>;
    members?: Array<Assignation>;
    parent?: Group;
    sourceRepositoryStatus?: any;
    sourceMembershipStatus?: any;
    pipelineFolderStatus?: any;
    binaryRepositoryStatus?: any;
}
