/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assignation } from './assignation';
import { Resource } from './resource';


export interface Group {
    id?: string;
    name?: string;
    status?: Group.StatusEnum;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: number;
    updatedAt?: number;
    metadata?: { [key: string]: any; };
    /**
     * Group's path in case of subgroup
     */
    path?: string;
    members?: Array<Assignation>;
    parent?: Group;
    sourceRepositoryStatus?: Group.SourceRepositoryStatusEnum;
    sourceMembershipStatus?: Group.SourceMembershipStatusEnum;
    pipelineFolderStatus?: Group.PipelineFolderStatusEnum;
    binaryRepositoryStatus?: Group.BinaryRepositoryStatusEnum;
}
export namespace Group {
    export type StatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        READY: 'READY' as StatusEnum,
        UPDATING: 'UPDATING' as StatusEnum,
        UNSTABLE: 'UNSTABLE' as StatusEnum,
        ERROR: 'ERROR' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    }
    export type SourceRepositoryStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const SourceRepositoryStatusEnum = {
        PENDING: 'PENDING' as SourceRepositoryStatusEnum,
        READY: 'READY' as SourceRepositoryStatusEnum,
        UPDATING: 'UPDATING' as SourceRepositoryStatusEnum,
        UNSTABLE: 'UNSTABLE' as SourceRepositoryStatusEnum,
        ERROR: 'ERROR' as SourceRepositoryStatusEnum,
        DELETED: 'DELETED' as SourceRepositoryStatusEnum
    }
    export type SourceMembershipStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const SourceMembershipStatusEnum = {
        PENDING: 'PENDING' as SourceMembershipStatusEnum,
        READY: 'READY' as SourceMembershipStatusEnum,
        UPDATING: 'UPDATING' as SourceMembershipStatusEnum,
        UNSTABLE: 'UNSTABLE' as SourceMembershipStatusEnum,
        ERROR: 'ERROR' as SourceMembershipStatusEnum,
        DELETED: 'DELETED' as SourceMembershipStatusEnum
    }
    export type PipelineFolderStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const PipelineFolderStatusEnum = {
        PENDING: 'PENDING' as PipelineFolderStatusEnum,
        READY: 'READY' as PipelineFolderStatusEnum,
        UPDATING: 'UPDATING' as PipelineFolderStatusEnum,
        UNSTABLE: 'UNSTABLE' as PipelineFolderStatusEnum,
        ERROR: 'ERROR' as PipelineFolderStatusEnum,
        DELETED: 'DELETED' as PipelineFolderStatusEnum
    }
    export type BinaryRepositoryStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const BinaryRepositoryStatusEnum = {
        PENDING: 'PENDING' as BinaryRepositoryStatusEnum,
        READY: 'READY' as BinaryRepositoryStatusEnum,
        UPDATING: 'UPDATING' as BinaryRepositoryStatusEnum,
        UNSTABLE: 'UNSTABLE' as BinaryRepositoryStatusEnum,
        ERROR: 'ERROR' as BinaryRepositoryStatusEnum,
        DELETED: 'DELETED' as BinaryRepositoryStatusEnum
    }
}
