/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiVersion } from './apiVersion';
import { Implementation } from './implementation';
import { Resource } from './resource';
import { SourceRepository } from './sourceRepository';


export interface ImplementationVersion extends Resource { 
    sourceRepo?: SourceRepository;
    version?: string;
    implementation?: Implementation;
    apiVersion?: ApiVersion;
}
