/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Asset } from './asset';
import { Component } from './component';
import { ImplementationVersion } from './implementationVersion';
import { Pipeline } from './pipeline';
import { SourceRepository } from './sourceRepository';


export interface Implementation {
    id?: string;
    name?: string;
    status?: Implementation.StatusEnum;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: number;
    updatedAt?: number;
    metadata?: { [key: string]: any; };
    sourceRepository?: SourceRepository;
    pipeline?: Pipeline;
    language?: Implementation.LanguageEnum;
    component?: Component;
    description?: string;
    title?: string;
    versions?: Array<ImplementationVersion>;
}
export namespace Implementation {
    export type StatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        READY: 'READY' as StatusEnum,
        UPDATING: 'UPDATING' as StatusEnum,
        UNSTABLE: 'UNSTABLE' as StatusEnum,
        ERROR: 'ERROR' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    }
    export type LanguageEnum = 'JAVA' | 'PYTHON';
    export const LanguageEnum = {
        JAVA: 'JAVA' as LanguageEnum,
        PYTHON: 'PYTHON' as LanguageEnum
    }
}
