/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiVersion } from './apiVersion';
import { Library } from './library';
import { Resource } from './resource';


export interface LibraryApiVersion {
    id?: string;
    name?: string;
    status?: LibraryApiVersion.StatusEnum;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: number;
    updatedAt?: number;
    metadata?: { [key: string]: any; };
    library?: Library;
    apiVersion?: ApiVersion;
    apiRepositoryStatus?: LibraryApiVersion.ApiRepositoryStatusEnum;
    pipelineStatus?: LibraryApiVersion.PipelineStatusEnum;
}
export namespace LibraryApiVersion {
    export type StatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        READY: 'READY' as StatusEnum,
        UPDATING: 'UPDATING' as StatusEnum,
        UNSTABLE: 'UNSTABLE' as StatusEnum,
        ERROR: 'ERROR' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    }
    export type ApiRepositoryStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const ApiRepositoryStatusEnum = {
        PENDING: 'PENDING' as ApiRepositoryStatusEnum,
        READY: 'READY' as ApiRepositoryStatusEnum,
        UPDATING: 'UPDATING' as ApiRepositoryStatusEnum,
        UNSTABLE: 'UNSTABLE' as ApiRepositoryStatusEnum,
        ERROR: 'ERROR' as ApiRepositoryStatusEnum,
        DELETED: 'DELETED' as ApiRepositoryStatusEnum
    }
    export type PipelineStatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const PipelineStatusEnum = {
        PENDING: 'PENDING' as PipelineStatusEnum,
        READY: 'READY' as PipelineStatusEnum,
        UPDATING: 'UPDATING' as PipelineStatusEnum,
        UNSTABLE: 'UNSTABLE' as PipelineStatusEnum,
        ERROR: 'ERROR' as PipelineStatusEnum,
        DELETED: 'DELETED' as PipelineStatusEnum
    }
}
