/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type LIBRARYTYPE = 'MODEL' | 'INTERFACE' | 'CLIENT';

export const LIBRARYTYPE = {
    MODEL: 'MODEL' as LIBRARYTYPE,
    INTERFACE: 'INTERFACE' as LIBRARYTYPE,
    CLIENT: 'CLIENT' as LIBRARYTYPE
};
