/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Membership { 
    path?: string;
    memberType?: Membership.MemberTypeEnum;
    memberName?: string;
    role?: Membership.RoleEnum;
}
export namespace Membership {
    export type MemberTypeEnum = 'user' | 'group';
    export const MemberTypeEnum = {
        User: 'user' as MemberTypeEnum,
        Group: 'group' as MemberTypeEnum
    };
    export type RoleEnum = 'guest' | 'contributor' | 'manager';
    export const RoleEnum = {
        Guest: 'guest' as RoleEnum,
        Contributor: 'contributor' as RoleEnum,
        Manager: 'manager' as RoleEnum
    };
}
