/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PackageTemplateArgument { 
    /**
     * Argument key to generate catalog entry
     */
    key?: string;
    /**
     * Argument value to generate catalog entry
     */
    value?: string;
    /**
     * Argument constraint
     */
    contrainst?: string;
}
