/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PIPELINETEMPLATE = 'JAVA_LIBRARY' | 'PYTHON_LIBRARY' | 'JAVA_SERVICE' | 'PYTHON_SERVICE';

export const PIPELINETEMPLATE = {
    JAVALIBRARY: 'JAVA_LIBRARY' as PIPELINETEMPLATE,
    PYTHONLIBRARY: 'PYTHON_LIBRARY' as PIPELINETEMPLATE,
    JAVASERVICE: 'JAVA_SERVICE' as PIPELINETEMPLATE,
    PYTHONSERVICE: 'PYTHON_SERVICE' as PIPELINETEMPLATE
}
