/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Resource } from './resource';
import { SourceRepository } from './sourceRepository';


export interface Pipeline {
    id?: string;
    name?: string;
    status?: Pipeline.StatusEnum;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: number;
    updatedAt?: number;
    metadata?: { [key: string]: any; };
    provider?: string;
    providerId?: string;
    credentialId?: string;
    path?: string;
    sourceRepository?: SourceRepository;
    template?: Pipeline.TemplateEnum;
}
export namespace Pipeline {
    export type StatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        READY: 'READY' as StatusEnum,
        UPDATING: 'UPDATING' as StatusEnum,
        UNSTABLE: 'UNSTABLE' as StatusEnum,
        ERROR: 'ERROR' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    }
    export type TemplateEnum = 'JAVA_LIBRARY' | 'PYTHON_LIBRARY' | 'JAVA_SERVICE' | 'PYTHON_SERVICE';
    export const TemplateEnum = {
        JAVALIBRARY: 'JAVA_LIBRARY' as TemplateEnum,
        PYTHONLIBRARY: 'PYTHON_LIBRARY' as TemplateEnum,
        JAVASERVICE: 'JAVA_SERVICE' as TemplateEnum,
        PYTHONSERVICE: 'PYTHON_SERVICE' as TemplateEnum
    }
}
