/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PIPELINETEMPLATE = 'JAVA_LIBRARY' | 'PYTHON_LIBRARY' | 'JAVA_SERVICE' | 'PYTHON_SERVICE' | 'HELM_PACKAGE' | 'DOCKER_SERVICE';

export const PIPELINETEMPLATE = {
    JAVALIBRARY: 'JAVA_LIBRARY' as PIPELINETEMPLATE,
    PYTHONLIBRARY: 'PYTHON_LIBRARY' as PIPELINETEMPLATE,
    JAVASERVICE: 'JAVA_SERVICE' as PIPELINETEMPLATE,
    PYTHONSERVICE: 'PYTHON_SERVICE' as PIPELINETEMPLATE,
    HELMPACKAGE: 'HELM_PACKAGE' as PIPELINETEMPLATE,
    DOCKERSERVICE: 'DOCKER_SERVICE' as PIPELINETEMPLATE
};
