/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PROGRAMMINGLANGUAGE = 'JAVA' | 'PYTHON';

export const PROGRAMMINGLANGUAGE = {
    JAVA: 'JAVA' as PROGRAMMINGLANGUAGE,
    PYTHON: 'PYTHON' as PROGRAMMINGLANGUAGE
}
