/**
 * Kathra Core Model
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-RC-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Resource {
    id?: string;
    name?: string;
    status?: Resource.StatusEnum;
    createdBy?: string;
    updatedBy?: string;
    createdAt?: number;
    updatedAt?: number;
    metadata?: { [key: string]: any; };
}
export namespace Resource {
    export type StatusEnum = 'PENDING' | 'READY' | 'UPDATING' | 'UNSTABLE' | 'ERROR' | 'DELETED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        READY: 'READY' as StatusEnum,
        UPDATING: 'UPDATING' as StatusEnum,
        UNSTABLE: 'UNSTABLE' as StatusEnum,
        ERROR: 'ERROR' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    }
}
