/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assignation } from './assignation';
import { Resource } from './resource';


export interface User extends Resource { 
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phone?: string;
    groups?: Array<Assignation>;
}
