/**
 * Kathra Applications Manager
 * Kathra Applications Manager
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Build } from '../model/build';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PipelinesService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Execute pipeline
     * 
     * @param pipelineId The ID of the Pipeline to get the builds of
     * @param branch The name of the branch to get the builds of
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public executePipeline(pipelineId: string, branch: string, observe?: 'body', reportProgress?: boolean): Observable<Build>;
    public executePipeline(pipelineId: string, branch: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Build>>;
    public executePipeline(pipelineId: string, branch: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Build>>;
    public executePipeline(pipelineId: string, branch: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pipelineId === null || pipelineId === undefined) {
            throw new Error('Required parameter pipelineId was null or undefined when calling executePipeline.');
        }

        if (branch === null || branch === undefined) {
            throw new Error('Required parameter branch was null or undefined when calling executePipeline.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (branch !== undefined && branch !== null) {
            queryParameters = queryParameters.set('branch', <any>branch);
        }

        let headers = this.defaultHeaders;

        // authentication (kathra_auth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<Build>(`${this.basePath}/pipelines/${encodeURIComponent(String(pipelineId))}/builds`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the builds for the given pipeline for a given branch
     * 
     * @param pipelineId The ID of the Pipeline to get the builds of
     * @param branch The name of the branch to get the builds of
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPipelineBuildsForBranch(pipelineId: string, branch: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Build>>;
    public getPipelineBuildsForBranch(pipelineId: string, branch: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Build>>>;
    public getPipelineBuildsForBranch(pipelineId: string, branch: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Build>>>;
    public getPipelineBuildsForBranch(pipelineId: string, branch: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pipelineId === null || pipelineId === undefined) {
            throw new Error('Required parameter pipelineId was null or undefined when calling getPipelineBuildsForBranch.');
        }

        if (branch === null || branch === undefined) {
            throw new Error('Required parameter branch was null or undefined when calling getPipelineBuildsForBranch.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (branch !== undefined && branch !== null) {
            queryParameters = queryParameters.set('branch', <any>branch);
        }

        let headers = this.defaultHeaders;

        // authentication (kathra_auth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Build>>(`${this.basePath}/pipelines/${encodeURIComponent(String(pipelineId))}/builds`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
